version: '3.8'

services:
  postgres:
    image: postgres:14.13
    volumes:
      - instrumentl-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - instrumentl
  web:
    build: .
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0' -p 3000'
    ports:
      - "3000:3000"
    volumes:
      - .:/instrumentl
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - instrumentl

networks:
  instrumentl:

volumes:
  instrumentl-postgres: